package org.omg.IOP;


/**
* org/omg/IOP/TAG_POLICIES.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-i586-cygwin/jdk8u162/10278/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Tuesday, December 19, 2017 7:00:05 PM PST
*/

public interface TAG_POLICIES
{

  /**
     * A profile component containing the sequence of QoS policies exported
     * with the object reference by an object adapter.
     */
  public static final int value = (int)(2L);
}
